### ISSUE TITLE
It is showing error while simulating the particles

### ISSUE THREAD

**Issue by 3DSinghVFX** [JacquesLucke/everything_nodes_prototype#1]
Hi Jacques,
Thanks for this addon. I have installed this addon on latest blender 2.79 build and I'm using Ubuntu 16.04 LTS. But it is showing error message while simulating the particles. I'm facing same the problem in blender 2.8 also. Please help.

![screenshot from 2018-06-25 20-50-52](https://user-images.githubusercontent.com/30294746/41859822-ad9ab42c-78ba-11e8-9c11-a66b6f36e22e.png)

**Comment by Lluc3D** [comment]
I have an error on 2.8 trying to create a simple particle node tree, i'm using windows:

```
NameError: name 'GL_POINT_SMOOTH' is not defined
Traceback (most recent call last):
File "C:\Users\lluc\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\everything_nodes_prototype\operators\simulate_particle_system.py", line 68, in draw_callback
    glEnable(GL_POINT_SMOOTH)
```

**Comment by Mrqozy** [comment]
Guys, I think for now it only works in the latest 2.79 experimental builds

**Comment by JacquesLucke** [comment]
https://youtu.be/10F9vQ09eQ0

Note: I won't continue to develop this addon. It was just me playing around while I were in Amsterdam at the Code Quest.
