### ISSUE TITLE
Will the new nodes API be functional?

### ISSUE THREAD

**Issue by loganpowell** [JacquesLucke/everything_nodes_prototype#2]
Very excited to see what you come up with for everything nodes. It seems like a perfect opportunity to bring a functional API (vs OOP) to Blender. Have you considered it?

**Comment by JacquesLucke** [comment]
Can you be more precise by what exactly you mean with a "functional API"? Or give an example.

**Comment by loganpowell** [comment]
Sure, as per your [post](https://wiki.blender.org/wiki/Source/Nodes/EverythingNodes):

> My plan is to start to integrate a generic function system. A function will probably be like a node group for Cycles, just more generic (i.e. it will be able to handle many more types of data). Additionally, different parts of Blender can become function users. A function user is able to use all functions that have a specific signature. A signature is the set of inputs and outputs of a function. This way, every tool in Blender that can use functions, automatically becomes much more flexible.

and on another [page](https://wiki.blender.org/wiki/Source/Nodes/InitialFunctionsSystem#Core_Architecture)

>  Every function should live as much as possible in a black box and only communicate with its environment in predefined ways. Other than that, it should be side effect free.

These are very much aligned with the [functional paradigm](https://en.wikipedia.org/wiki/Functional_programming), which is even easier to abide by in [Python 3+](https://docs.python.org/3/howto/functional.html)

I know that classes are the touchstone of Blender's API, but you have the special opportunity to bring in a "sub API", which embraces immutability and data-flow instead of mutable state and class boilerplate.

Here's an [existing node](https://github.com/JacquesLucke/animation_nodes/blob/master/animation_nodes/nodes/geometry/barycentric_transform.py)

This is already very functional. You have some local variables and the rest are functions, but you don't return anything from the function, but rather mutate the inputs (e.g., `self.newOutput`. What if - instead - you just took data in and then returned data out for consumption by another node or rendering in the UI? Perhaps you could pass the relevant parts of the environment (including those provided to the node by other nodes) in as arguments instead and just returned data that could be used by following nodes.

You might use [function annotations](https://realpython.com/python-type-checking/#function-annotations) for type-checking to ensure the nodes are compatible...

**Comment by JacquesLucke** [comment]
Nodes are generally just functions, which follow the functional programming paradigm. This is in fact, what I already implemented. However, it is not used in the Python API yet.

So yeah, I'm well aware of this paradigm and will use it, whenever it makes sense.

**Comment by loganpowell** [comment]
Ah, you mean in C?

**Comment by JacquesLucke** [comment]
yes, and c++

**Comment by loganpowell** [comment]
🙌 can't wait to see the new Python API! Where do I sign up to keep up to date with your work?

**Comment by JacquesLucke** [comment]
I (and the other devs paid by fund.blender.org) write weekly reports about what we do. They are linked in the weekly meeting notes.

**Comment by loganpowell** [comment]
This? https://wiki.blender.org/wiki/User:JacquesLucke/Reports/2019#Week_40:_July_01_-_05

**Comment by JacquesLucke** [comment]
yes

**Comment by loganpowell** [comment]
Thank you sir
